project:
  type: website
  output-dir: _site

website:
  title: "PGA Tour Putting Performance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: explorer.qmd
        text: Tour Exploration
      - href: story.qmd
        text: The Scheffler Paradox
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
